name: Run linters and tests
on: [push, workflow_call, workflow_dispatch]
jobs:

  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run linter
        run: tox -e flake8

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        tox-env: ['27', '35', '36', '37', '38', '39', '310', '311']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tests
        run: tox -e "py${{ matrix.tox-env }}-{oldest,latest}"

  trigger-publish:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    needs: [run-linters, run-tests]
    uses: ./.github/workflows/publish.yml
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
